### ISSUE TITLE
[BUG] kbcli connect nebula error: fail to get the target engine type 

### ISSUE THREAD

**Issue by JashBook** [apecloud/kbcli#214]
**Describe the bug**
```
 kbcli version
Kubernetes: v1.26.3
KubeBlocks: 0.8.0-beta.48
kbcli: 0.8.0-beta.42
```

**To Reproduce**
1. create cluster
```
apiVersion: apps.kubeblocks.io/v1alpha1
kind: Cluster
metadata:
  name: nebula-ngmyta
  namespace: default
spec:
  clusterDefinitionRef: nebula
  clusterVersionRef: nebula-v3.5.0
  terminationPolicy: Halt
  componentSpecs:
    - name: nebula-console
      componentDefRef: nebula-console
      replicas: 2
      resources:
        requests:
          cpu: 100m
          memory: 0.5Gi
        limits:
          cpu: 100m
          memory: 0.5Gi
    - name: nebula-graphd
      componentDefRef: nebula-graphd
      replicas: 1
      resources:
        requests:
          cpu: 100m
          memory: 0.5Gi
        limits:
          cpu: 100m
          memory: 0.5Gi
      volumeClaimTemplates:
        - name: logs
          spec:
            storageClassName:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 1Gi
    - name: nebula-metad
      componentDefRef: nebula-metad
      replicas: 3
      resources:
        requests:
          cpu: 100m
          memory: 0.5Gi
        limits:
          cpu: 100m
          memory: 0.5Gi
      volumeClaimTemplates:
        - name: data
          spec:
            storageClassName:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 1Gi
        - name: logs
          spec:
            storageClassName:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 1Gi
    - name: nebula-storaged
      componentDefRef: nebula-storaged
      replicas: 3
      resources:
        requests:
          cpu: 100m
          memory: 0.5Gi
        limits:
          cpu: 100m
          memory: 0.5Gi
      volumeClaimTemplates:
        - name: data
          spec:
            storageClassName:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 1Gi
        - name: logs
          spec:
            storageClassName:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 1Gi
```
2. See error
```
kbcli cluster connect nebula-ngmyta
error: fail to get the target engine type
```

**Expected behavior**
kbcli connect nebula success.

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**
