### ISSUE TITLE
[BUG] kbcli custom-ops kafka-topic not supports the component broker

### ISSUE THREAD

**Issue by JashBook** [apecloud/kbcli#215]
**Describe the bug**

**To Reproduce**
1. create cluster
```
apiVersion: apps.kubeblocks.io/v1alpha1
kind: Cluster
metadata:
  name: kafka-qlcjhp
  namespace: default
spec:
  clusterDefinitionRef: kafka
  clusterVersionRef: kafka-3.3.2
  terminationPolicy: Halt
  componentSpecs:
    - name: broker
      componentDef: kafka-combine-server
      replicas: 3
      resources:
        requests:
          cpu: 500m
          memory: 0.5Gi
        limits:
          cpu: 500m
          memory: 0.5Gi
      volumeClaimTemplates:
        - name: data
          spec:
            storageClassName:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 1Gi
        - name: metadata
          spec:
            accessModes:
            - ReadWriteOnce
            resources:
              requests:
                storage: 1Gi
```
2. See error
```
kbcli cluster custom-ops kafka-topic --cluster kafka-qlcjhp --type create --topic testt --partitions 2 --component broker
args: [kafka-topic --cluster kafka-qlcjhp --type create --topic testt --partitions 2 --component broker]
error: this custom ops "kafka-topic" not supports the component "broker"
```

**Expected behavior**
kbcli custom-ops kafka-topic  success.

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**
