### ISSUE TITLE
[BUG] kbcli connect zookeeper cluster error: unsupported engine type: zookeeper

### ISSUE THREAD

**Issue by JashBook** [apecloud/kbcli#235]
**Describe the bug**
```
kbcli version
Kubernetes: v1.26.6-gke.1700
KubeBlocks: 0.8.0
kbcli: 0.8.0
```

**To Reproduce**
1. install cluster zookeeper
```
apiVersion: apps.kubeblocks.io/v1alpha1
kind: Cluster
metadata:
  name: zkeeper-pbmwtr
  namespace: default
spec:
  clusterDefinitionRef: zookeeper
  clusterVersionRef: zookeeper-3.7.2
  terminationPolicy: DoNotTerminate
  componentSpecs:
    - name: zookeeper
      componentDefRef: zookeeper
      replicas: 2
      resources:
        requests:
          cpu: 100m
          memory: 0.5Gi
        limits:
          cpu: 100m
          memory: 0.5Gi
      volumeClaimTemplates:
        - name: data
          spec:
            storageClassName:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 1Gi
        - name: data-log
          spec:
            storageClassName:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 1Gi
```
2. See error
```
kbcli cluster connect zkeeper-pbmwtr 
Connect to instance zkeeper-pbmwtr-zookeeper-0: out of zkeeper-pbmwtr-zookeeper-0, zkeeper-pbmwtr-zookeeper-1
error: unsupported engine type: zookeeper
```

**Expected behavior**
kbcli connect zookeeper cluster success

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**
