### ISSUE TITLE
[BUG] kbcli connect ob cluster error: fail to get the target engine type

### ISSUE THREAD

**Issue by JashBook** [apecloud/kbcli#309]
**Describe the bug**

**To Reproduce**
1. create cluster 
```
apiVersion: apps.kubeblocks.io/v1alpha1
kind: Cluster
metadata:
  name: obce-qmntco
  namespace: default
  annotations:
    "kubeblocks.io/extra-env": '{"TENANT_NAME":"tenant2","ZONE_COUNT":"1","OB_CLUSTERS_COUNT":"2","TENANT_CPU":"2","TENANT_MEMORY":"2G","TENANT_DISK":"5G"}'
spec:
  terminationPolicy: DoNotTerminate
  componentSpecs:
    - name: ob-ce-0
      componentDefRef: ob-ce
      componentDef: ob-ce-repl
      replicas: 1
      resources:
        requests:
          cpu: 3000m
          memory: 8Gi
        limits:
          cpu: 3000m
          memory: 8Gi
      volumeClaimTemplates:
        - name: data-file
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: "50Gi"
        - name: data-log
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: "50Gi"
        - name: log
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: "10Gi"
        - name: workdir
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: "100Mi"
    - name: ob-ce-1
      componentDefRef: ob-ce
      componentDef: ob-ce-repl
      replicas: 1
      resources:
        requests:
          cpu: 3000m
          memory: 8Gi
        limits:
          cpu: 3000m
          memory: 8Gi
      volumeClaimTemplates:
        - name: data-file
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: "50Gi"
        - name: data-log
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: "50Gi"
        - name: log
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: "10Gi"
        - name: workdir
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: "100Mi"
```
2. See error
```
kbcli cluster connect obce-qmntco 
error: fail to get the target engine type

kbcli cluster connect  -i obce-qmntco-ob-ce-0-0
error: fail to get the target engine type
```

**Expected behavior**
kbcli connect ob cluster success

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**
