### ISSUE TITLE
[BUG]kbcli cluster expose asmysql-slppbv failed with error: unrecognized type: string

### ISSUE THREAD

**Issue by tianyue86** [apecloud/kbcli#555]
**Describe the env**
Kubernetes: v1.31.1-aliyun.1
KubeBlocks: 1.0.0-beta.28
kbcli: 1.0.0-beta.11

**To Reproduce**
1. Create mysql cluster in running status
```
apiVersion: apps.kubeblocks.io/v1
kind: Cluster
metadata:
  name: asmysql-slppbv
  namespace: default
spec:
  clusterDef: mysql
  topology: semisync
  terminationPolicy: WipeOut
  componentSpecs:
    - name: mysql
      serviceVersion: 8.0.30
      
      disableExporter: true
      replicas: 2
      resources:
        limits:
          cpu: 100m
          memory: 0.5Gi
        requests:
          cpu: 100m
          memory: 0.5Gi
      volumeClaimTemplates:
        - name: data
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 20Gi
```
2. check cluster status
```
k get cluster -A
NAMESPACE   NAME                   CLUSTER-DEFINITION   TERMINATION-POLICY   STATUS     AGE
default     asmysql-slppbv         mysql                WipeOut              Running    47s
```
3. expose it -> error
```
kbcli cluster expose asmysql-slppbv --auto-approve --force=true                  --type intranet --enable true                 --components mysql  --namespace default
error: unrecognized type: string
```

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**
